### ISSUE TITLE
Missing tell method

### ISSUE THREAD

**Issue by marek22k** [philr/bzip2-ffi#2]
Hello,

when I want to skip a block of data, I currently do `from.pos = from.tell + len`, where `from` is the stream and `len` is the number of bytes I want to skip. However, when I do it this way, the following error appears:
```
NoMethodError: undefined method `tell' for #<Bzip2::FFI::Reader:0x00007f5067c184a0 @io=#<File:master6_latest.mrt.bz2>, @autoclose=true, @stream=#<Bzip2::FFI::Libbz2::BzStream:0x00007f5067c07e48>, @first_only=nil, @small=0, @in_eof=false, @out_eof=false, @in_buffer=nil, @structure_number=1, @structure_start_pos=0, @in_pos=0, @out_pos=0>
```
Is there another function the skip data?

**Comment by philr** [comment]
The [`Reader#pos`](https://www.rubydoc.info/gems/bzip2-ffi/1.1.0/Bzip2/FFI/Reader#pos-instance_method) method can be used to determine the current position.

However, there's no `pos=` implementation and no support for seeking. You'll need to read and discard the data you want to skip with `from.read(len)`. That will end up allocating a buffer and a string of length `len` (assuming at least `len` bytes are available to be read). If `len` is large, it would might be better to perform multiple smaller reads.

**Comment by marek22k** [comment]
Will there be support for seeking?

**Comment by philr** [comment]
The underlying libbzip2 library doesn't support seeking. If support was to be added to bzip2-ffi, it'd have to only support seeking forwards and perform the seek by issuing reads to libbzip2.
